baseURL = "https://www.barrymarries.com/"
languageCode = "en-us"
relativeURLs = true
sectionPagesMenu = "main"
theme = "hugo-theme-barrymarries"
title = "Barry Marries!"
[[menu.main]]
identifier = "officiating"
name = "Officiating"
parent = "Services"
url = "/services/officiating/"
weight = 1
[[menu.main]]
identifier = "contact"
name = "Contact Me"
url = "/contact-me/"
weight = 4
[[menu.main]]
identifier = "services"
name = "Services"
url = "/services/"
weight = 3
[[menu.main]]
identifier = "about"
name = "About Barry"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
copyrighthtml = "Content &copy;  <script>document.write(new Date().getFullYear())</script>, Barry Smith. All Rights Reserved."
theme = "simplex"
#fa_pro_url = "https://kit.fontawesome.com/92d57ef7ed.js"
