baseURL = "https://www.barrymarries.com/"
languageCode = "en-us"
title = "Barry Marries!"
theme = "hugo-theme-barrymarries"
relativeURLs = true
sectionPagesMenu = "main"

[params]
  theme = "lux"
  copyrighthtml = "Content &copy;  <script>document.write(new Date().getFullYear())</script>, Barry Smith. All Rights Reserved."